### PR TITLE
Add support for values without schema

### PR DESCRIPTION
**Pull request by pbamba**
Hi @jcustenborder !

Here's a first draft as a solution to the following problem.

When using value converters like the JsonConverter without a schema, I get a NullPointerException because building an archive requires the value to have a schema.
Therefore I've just added to apply methods (with and without schema) to handle both cases.
I've looked at other kafka connect transforms for inspiration 😃 

I'm looking forward for your feedback especially since it's my first time contributing to a kafka connect project !

Patrick

### CODE REVIEW

**Comment by pbamba** [comment]
Hi @jcustenborder, did you get a chance to take a look at this ?

**Comment by jcustenborder** [comment]
@pbamba Sorry about the delay.

**Comment by jcustenborder** [comment]
LGTM

**Comment by pbamba** [comment]
@jcustenborder no problem. Thanks for the merge!

**Pull request merged**
